# Generated by Django 3.2.5 on 2021-07-31 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kapasitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=8)),
                ('kapasitas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('sks', models.IntegerField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Pengajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Sesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pengajar_Matkul_Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.kelas')),
                ('no_matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.matkul')),
                ('no_pengajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pengajar')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_PMK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pengajar_matkul_kelas')),
                ('no_akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.akun')),
                ('no_hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hari')),
                ('no_sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sesi')),
            ],
        ),
    ]
